# workers/Master-Pull/wrangler.toml 
name = 'master-pull'
main = "pim-master-pull-v3.js"
compatibility_date = "2026-01-08"

# D1 binding (AUTH DB)
[[d1_databases]]
binding = "DB"
database_name = "pim3"
database_id = "ae86a3c9-7835-4c2e-9bde-96a53ef481b4"

[[r2_buckets]]


[observability]
[observability.logs]
enabled = true
invocation_logs = true

[vars]
