name = "pim-app-worker"
main = "pim-app-worker.js"
compatibility_date = "2026-01-08"

# D1 binding
[[d1_databases]]
binding = "DB"
database_name = "pim3"
database_id = "ae86a3c9-7835-4c2e-9bde-96a53ef481b4"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[vars]
APP_URL = "https://pim-app-worker.patrickwjmans.workers.dev"
SHOPIFY_API_KEY = "97ef055bf2c68ccd4fabbb6af76fa65f"
SHOPIFY_API_SECRET = "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"